version: '3'
services:
  llama-app-fastapi:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://user:password@db:5432/llama_app_db
    volumes:
      # allows for live reloading of the app
      # when the code within the ./app directory changes
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost", "http://localhost:8000", "http://192.168.176.5:3000","http://localhost:3000","http://finbot.turnkeyafrica.com", "https://finbot.turnkeyafrica.com"]'
    networks:
      - llama

  db:
    image: ankane/pgvector:v0.5.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llama_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - llama

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - llama

volumes:
  postgres_data:

networks:
  llama: